###Create currencies

POST http://localhost:8080/currency
Content-Type: application/json

{
  "code":"EUR",
  "text" : "Євро"
}

> {% client.test("Successful POST Request", function (){
    client.assert(response.status === 201, "Response Status is not 201")
}) %}

### Create currencies
POST http://localhost:8080/currencies
Content-Type: application/json

[
  {
    "code": "USD",
    "text": "Долар"
  },
  {
    "code": "AUD",
    "text": "Австралійський долар"
  }
]



> {% client.test("Successful POST Request", function (){
    client.assert(response.status === 201, "Response Status is not 201")
}) %}


###Create daily rates for interesting currencies
POST http://localhost:8080/rates?date=20221211
Content-Type: application/json